---
title: Events
format:
  html:
    execute:
    echo: false
    css: events.css   
---

## Upcoming Events

___



Example table format using knitr

```{r}
df <- data.frame(Title = c('A', 'B', 'B', 'B', 'B', 'A'),
    Dates = c('Aug 20, 2024', 'Aug 12, 2024', 'Aug 2, 2024', 'Aug 1, 2024', 'Eric', 'Frank'),
    Location = c(1, 2, 2, 1, 0, 0),
    Type = c(1, 1, 1, 1, 1, 1))

#view data frame
knitr::kable(df[1:6, ], )
```


<table><tbody><tr><td>Title</td><td>Dates</td><td>Location</td><td>Type</td>
</tr>

<tr><td><a href="https://datacove.co.uk/earl-2024-tech-conference/" target="_blank" rel="noreferrer noopener">EARL 2024</a></td><td>September 4-5, 2024</td><td>Brighton, UK</td><td>Conference</td></tr>
<tr><td><a href="https://shiny-in-production.jumpingrivers.com/" target="_blank" rel="noreferrer noopener">Shiny in Production 2024</a></td><td>October 9-10, 2024</td><td>Newcastle upon Tyne, UK</td><td>Conference</td></tr>
<tr><td><a href="https://actuaries.org.uk/call-for-speakers/#life-conference" target="_blank" rel="noreferrer noopener">IFoA Life Conference 2024</a></td><td>October 14-16, 2024</td><td>Manchester, UK</td><td>Conference</td></tr>
<tr><td><a href="https://rstats.ai/gov" target="_blank" rel="noreferrer noopener">2024 Government &amp; Public Sector R Conference</a></td><td>October 29-30, 2024</td><td>Washington D.C., USA</td><td>Conference</td></tr>

</tbody></table>

## Recently Completed Events

___

<table><tbody><tr><td>Title</td><td>Dates</td><td>Location</td><td>Type</td></tr>

<tr><td><a href="https://www.r-project.org/conferences/" target="_blank" rel="noreferrer noopener">useR! 2024</a></td><td>July 8-11, 2024</td><td>Salzburg, Austria</td><td>Conference</td></tr>
<tr><td><a href="https://posit.co/" target="_blank" rel="noreferrer noopener">posit::conf 2024</a></td><td>August 12-14, 2024</td><td>Seattle, WA, USA</td><td>Conference</td></tr>

<tr><td>Henrick Bengtsson invited to speak at the Swiss Re Conference</td><td>June 25, 2024 – 7:00 AM ET</td><td>Virtual</td><td>Conference</td></tr>
<tr><td><a href="https://cascadiarconf.com/">Cascadia R Conference</a></td><td>June 21-22, 2024</td><td>Seattle, WA, USA</td><td>Conference</td></tr>
<tr><td><a href="https://www.rstats.nyc/" target="_blank" rel="noreferrer noopener">New York R Conference</a></td><td>May 16-17, 2024</td><td>New York City, NY, USA</td><td>Conference</td></tr>
<tr><td><a href="https://www.rinfinance.com/" target="_blank" rel="noreferrer noopener">R/Finance 2024</a></td><td>May 17-18, 2024</td><td>Chicago, IL, USA</td><td>Conference</td></tr>
<tr><td><a href="https://satrday-london-2024.jumpingrivers.com/" target="_blank" rel="noreferrer noopener">SatRdays London 2024</a></td><td>April 27, 2024</td><td>London, UK</td><td>Conference</td></tr>
<tr><td><a href="https://www.r-consortium.org/r-medicine-quarto-for-reproducible-medical-manuscripts">R/Medicine: Quarto for Reproducible Medical Manuscripts</a></td><td>March 20, 2024</td><td>Virtual</td><td>Webinar</td></tr>
<tr><td><a href="https://www.r-consortium.org/new-webinar-tidy-finance-and-accessing-financial-data" target="_blank" rel="noreferrer noopener">New Webinar: Tidy Finance and Accessing Financial Data</a></td><td>March 6, 2024</td><td>Virtual</td><td>Webinar</td></tr>
<tr><td><a href="https://www.r-consortium.org/escape-the-data-dungeon-unlock-scalable-r-analytics-and-ml" target="_blank" rel="noreferrer noopener">Escape the Data Dungeon: Unlock Scalable R Analytics and ML</a></td><td>February 27, 2024</td><td>Virtual</td><td>Webinar</td></tr>
<tr><td><a href="https://www.r-consortium.org/from-vision-to-action-the-r-pfizer-r-center-of-excellence-led-journey-to-r-adoption" target="_blank" rel="noreferrer noopener">From Vision to Action: The Pfizer R Center of Excellence-led journey to R Adoption</a></td><td>February 8, 2024</td><td>Virtual</td><td>Webinar</td></tr>
<tr><td><a href="https://www.r-consortium.org/r-insurance-series-for-everyone-in-insurance-or-actuarial-science" target="_blank" rel="noreferrer noopener">R/Insurance Series: High performance programming in R</a></td><td>January 31, 2024</td><td>Virtual</td><td>Webinar</td></tr>
<tr><td><a href="https://www.r-consortium.org/r-insurance-series-for-everyone-in-insurance-or-actuarial-science">Dan Sjoberg presenting on Plotting Survival with {ggsurvfit}</a></td><td>January 25, 2024</td><td>Virtual</td><td>Webinar</td></tr>
<tr><td><a href="https://www.r-consortium.org/r-insurance-series-for-everyone-in-insurance-or-actuarial-science">R/Insurance Series:&nbsp;R performance culture</a></td><td>January 24, 2024</td><td>Virtual</td><td>Webinar</td></tr>
<tr><td><a href="https://www.r-consortium.org/r-insurance-series-for-everyone-in-insurance-or-actuarial-science">R/Insurance Series: From programming in R to putting R into production</a></td><td>January 17, 2024</td><td>Virtual</td><td>Webinar</td></tr>
<tr><td><a href="https://www.r-consortium.org/r-insurance-series-for-everyone-in-insurance-or-actuarial-science">R/Insurance Series:&nbsp;From Excel to Programming in R</a></td><td>January 10, 2024</td><td>Virtual</td><td>Webinar</td></tr>
<tr><td><a href="https://www.r-consortium.org/r-adoption-series-the-adoption-of-r-in-japans-pharma-industry-confirmation">The use of R in Japan’s Pharma Industry</a></td><td>January 8, 2024</td><td>Virtual</td><td>Webinar</td></tr>

</tbody></table>

## Archived Webinars

___

[**R and shiny in regulatory submissi**](https://www.r-consortium.org/r-adoption-series-r-and-shiny-in-regulatory-submissions-webinar)[**on**](https://www.r-consortium.org/r-adoption-series-r-and-shiny-in-regulatory-submissions-webinar) – December, 11 2023 • Virtual

This series was a collaborative effort by the R consortium, PhUSE, and PSI. The FDA and industry speakers shared their unique experiences with R-based and shiny-based submissions.

[**PHUSE EU Connect 2023**](https://www.phuse-events.org/attend/frontend/reg/thome.csp?pageID=11403&eventID=19) – Nov 5 – 8, 2023 • Birmingham, UK

The PHUSE EU Connect 2023 was a key event for professionals in healthcare data science.

[**R/Pharma**](http://rinpharma.com/) – Oct 24 – 26, 2023 • Virtual

The R/Pharma conference in 2023 was a specialized event focusing on the use of R in pharmaceutical development.

[**R government**](https://rstats.ai/gov) – October 19 – 20, 2023 • Washington DC

The 2023 Government & Public Sector R Conference was an event dedicated to exploring the use of the R programming language in government and public sector contexts. It featured a diverse lineup of speakers and workshops, focusing on various applications of R, including data analysis, machine learning, and policy research. The conference provided a platform for professionals and enthusiasts to share insights, innovations, and experiences in applying R in governmental and public sector projects.

[**LatinR 2023**](https://latin-r.com/en) – October 18 – 20, 2023 • Montevideo, Uruguay

LatinR 2023 was a Latin American conference focusing on the use of the R programming language in research and development.

[**Shiny in Production**](https://shiny-in-production.jumpingrivers.com/) – October 12 – 13, 2023 • Newcastle, UK

The “Shiny in Production” conference, which took place in Newcastle Upon Tyne, UK, was centered around the application of Shiny and other web-based R packages. It attracted a diverse group of participants, ranging from experienced Shiny users to novices.

[**BioC Europe**](https://eurobioc2023.bioconductor.org/) – September 20 – 22, 2023 • Heidelberg, Germany

The European Bioconductor Conference 2023 is centered on new developments in the Bioconductor project and related fields of bioinformatics and computational biology. It includes workshops and keynote presentations for knowledge sharing and collaboration.

[**Posit:conf**](https://posit.co/conference/) – September 17 – 20, 2023 • Chicago, IL

Posit::conf (2023) was two days of workshops and two days of conference keynotes and talks, with endless opportunities to connect with the data science community.

**[R Validation Hub Community Meeting](https://www.r-consortium.org/blog/2023/06/14/learnings-and-reflection-from-case-studies-what-is-next-for-the-r-validation-hub)** – June 27, 2023 • Virtual

Last year, the R validation hub initiated a three-part presentation series on “case studies.” Eight pharma companies presented their implementation of the risk assessment framework. We briefly summarize common themes and differences in the approaches. For the majority of the meeting, we want to discuss common challenges and brainstorm ideas for possible future projects by the R Validation Hub.

[**R/Medicine 2023 Virtual Conference**](https://events.linuxfoundation.org/r-medicine/) – June 5-9, 2023 • Virtual

The R/Medicine conference provides a forum for sharing R based tools and approaches used to analyze and gain insights from health data.

**SatRday – Hosted By Jumping Rivers** – April 22, 2023 • Hosted at King’s College London, UK

Hosted at King’s College, UK, this one-day event will feature talks on all things R! SatRdays events are for everyone with an interest in R, whether you’re a seasoned pro or just getting started. [Learn More](https://satrday-london-2023.jumpingrivers.com/)

**[R/Adoption Series: Learnings and Reflection from R Validation Case Studies](https://www.r-consortium.org/r-adoption-series-learnings-and-reflection-from-r-validation-case-studies)** – March 30, 2023 • Virtual

The R Validation Hub will review the implementation of risk-based approaches to assess R package accuracy within a validated infrastructure and present our learnings from applied case studies. The discussion reflects the thinking of the R Validation Hub working group, which is a cross-industry initiative funded by the R Consortium.

**[Teal: An R-Shiny Framework to Unlock the Power of Interactive Data Exploration](https://www.r-consortium.org/r-adoption-series-teal-an-r-shiny-framework-interactive-data-exploration)** – Feb 23, 2023 • Virtual

Teal is an open-source framework for building interactive data exploration applications in R. Developed at Roche, Teal allows users to quickly and easily create dynamic visualizations and tabulations of their data. It provides a range of pre-built, customizable modules and enables users to interact with their data in real time. This allows users to quickly and easily explore their data, thus enabling fast insights generation.

**[{MMRM} and Software Engineering Working Group](https://www.r-consortium.org/r-adoption-series-introducing-the-software-engineering-working-group-and-mmrm)** – Jan 26, 2023 • Virtual

In this R Adoption Series Webinar, the R Consortium invites the ASA Software Engineering Working Group ASA BIOP SWE to share their experience of how the group formed and the types of problems they are trying to solve in the Open Source for the Pharmaceutical industry.

[**Using R at Scale on Database Data**](https://www.r-consortium.org/r-database-using-r-at-scale-on-database-data) – December 8, 2022 • Virtual

In this webinar, Mark and Sherry present on how to increase overall solution performance with R tightly integrated with Oracle databases.

**[A Survey of Changes around the Tidyverse Package in R](https://www.r-consortium.org/blog/2022/10/24/a-survey-of-changes-around-the-tidyverse-package-in-r)** – October 28, 2022 • Virtual

The Osun RUG, Nigeria hosts “A Survey of Changes around the Tidyverse Package in R” with special guest, Chief Scientist at RStudio, Hadley Wickham. The core tidyverse includes the packages that is likely used in everyday data analyses.

**[Upskilling on Data Handling and Communication at Swiss Re](https://hopin.com/events/r-insurance-webinar-78ebfbb8-e585-4e25-94dd-00ef94fe27a3)** – October 27, 2022 • Virtual

In this session, Swiss Re team members shared their approach to upskilling for data analytics before diving into an example of how to create automated (and stunning) actuarial reports. [More Information](https://www.r-consortium.org/webinars)

**[Using Metadata for Speedy Delivery](http://hopin.com/events/using-metadata-for-speedy-delivery-c2a8b27e-ba3e-47dc-aeb3-b80550fb105d)** – September 29, 2022 • Virtual

In this R Adoption Series Webinar, the R Consortium invited two Pharmaceutical organizations to share their experience in leveraging metadata for automation pieces of the clinical delivery workflow. [More Information](https://www.r-consortium.org/webinars)

**[R/Medicine Conference 2022!](https://events.linuxfoundation.org/r-medicine/)** – August 23 – 26, 2022 • Virtual

Announcing [R/Medicine 2022](https://events.linuxfoundation.org/r-medicine/)! The conference was fully virtual from August 23 through 26 and featured two days of workshops (included with the low registration fee!) and two days of keynotes featuring JJ Allaire and Frank Harrell. Check out the [R Consortium Youtube](https://www.youtube.com/r-consortium) to view the talks!

**[Rstudio::conf 2022](https://www.rstudio.com/conference/)** – July 25-28, 2022 • Washington DC

A conference to connect, learn and celebrate all things R and RStudio! Sharpen your skills and celebrate the R Community together with an array of workshops and an inspiring lineup of speakers.

**[userR! 2022](https://user2022.r-project.org/)**  – June 20 – 23, 2022 • Virtual

Now in its 18th year is the official conference of the R Project for Statistical Computing. Keynotes include Sebastian Meyer, Amanda Cox, Julia Silge, Mine Dogucu and will showcase the [afrimapr](https://afrimapr.github.io/afrimapr.website/) project supports the development of a community of practice in Africa around map-making in R

**R Conference** – June 8-10, New York

A conference that gathers data scientists and data professionals to explore, share, and inspire ideas, and to promote the growth of open source ideals

**IDEA, The R Consortium working group on Inclusion, Diversity, Equity, and Accessibility** – June 4 

Will be holding francophone [satRdays](https://satrdays.org/) event. More information should be available on the [R Consortium Blog](https://www.r-consortium.org/news/blog) shortly

**R/ Finance** – June 3-4, Chicago

One of the longest-running R conferences is the primary meeting for academics and Quants using R for finance. This single-track event is the place to talk time series, stochastic modeling, and meet some legendary R developers.

**R Adoption Series: Reporting Table Creation In R: Meeting Specific Needs With a General Framework** – Apr 28, 8-9:30am PDT / 11am-12:30pm EDT / 4-5:30pm BST

Gabriel Becker, Scientist in the Bioinformatics and Computational Biology department at Genentech Research.

Gabe will present the rtables package in three contexts. First, he will briefly present the package itself and how it can be used to create reporting tables, including those suitable for regulatory submissions. He will then discuss where rtables fits in the larger process of filing-table creation within Roche. Finally, he will pivot to discussing what contributed to rtables’ success as a general framework intended to meet specific needs and what lessons those in Industry can draw from its development. 

Register [here](https://hopin.com/events/the-r-adoption-series) or [see the webinar home page](https://www.r-consortium.org/webinars) for details.