---
title: "Empowering R Enthusiasts: SatRDays London 2024 Unveiled"
description: "SatRDays London 2024 is set to ignite the data science community with a vibrant lineup of speakers and a rich array of topics ranging from survival analysis to geospatial data.…"
author: "R Consortium"
image: ""
date: "03/28/2024"
format:
  html:
    css: 
      - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css
---

SatRDays London 2024 is set to ignite the data science community with a vibrant lineup of speakers and a rich array of topics ranging from survival analysis to geospatial data. This inclusive event, designed for R enthusiasts at all levels, emphasizes networking and collaboration amidst the backdrop of King’s College London’s iconic Bush House. Keynote speakers like Andrie de Vries, Nicola Rennie, and Matt Thomas bring unparalleled expertise, offering attendees a unique opportunity to deepen their knowledge and connect with peers. As a hub of innovation and learning, SatRDays London promises to be a cornerstone event for anyone passionate about R and its applications in the real world.


### [Register Now!](https://satrdays-london-2024.jumpingrivers.com/#registration)

**How does this year’s satRDays in London compare to last year’s event? What’s new and different?**

After a successful SatRdays London in 2023, we are keeping the format the same, but with a whole new lineup of speakers! This year we’re excited to welcome: 



* Andrie de Vrie – Posit
* Hannah Frick – Posit
* Charlie Gao – Hibiki AI Limited
* Michael Hogers – NPL Markets Ltd
* Matthew Lam & Matthew Law – Mott MacDonald
* Myles Mitchell – Jumping Rivers
* Nicola Rennie – Lancaster University
* Matt Thomas – British Red Cross

Talk topics for the day include survival analysis, geospatial data, styling PDFs with Quarto and using R to teach R, as well as a range of other exciting themes! The talks can reach a varied audience from aspiring data scientists right to the experienced audiences.

Take a look at the full list on the [conference website](https://satrdays-london-2024.jumpingrivers.com/) for more information.

**Who should attend? And what types of networking and collaboration opportunities should attendees expect?**

Anyone and everyone with an interest in R! The SatRdays conferences are designed to be low cost, to allow as many to attend as possible, and they’re on a SatRday, so you don’t have to worry about getting time off work if your job isn’t necessarily R focussed.

Networking is the main focus of the event. We have multiple coffee breaks to give attendees the opportunity to interact with fellow R enthusiasts. If you’re brand new to this kind of event, and are not sure where to start, don’t worry! Find one of the attendees from JR, and we’ll be happy to help you make introductions! 

**Can you share some insights into the keynote speakers, their areas of expertise, and how they will contribute to the overall experience at SatRDays?**

At this year’s event, we have talks from three invited speakers – Andrie de Vries of Posit, Nicola Rennie from the University of Lancaster and Matt Thomas of the British Red Cross.

Andrie is Director of Product Strategy at Posit (formerly RStudio) where he works on the Posit commercial products. He started using R in 2009 for market research statistics, and later joined Revolution Analytics and then Microsoft, where he helped customers implement advanced analytics and machine learning workflows.                 

Nicola is a lecturer in health data science based at the Centre for Health Informatics, Computing, and Statistics at Lancaster University. She is particularly interested in creating interactive, reproducible teaching materials and communicating data through effective visualisation. Nicola also collaborates with the NHS on analytical and software engineering projects, maintains several R packages, and organises R-Ladies Lancaster.

Matt is Head of Strategic Insight & Foresight at the British Red Cross. His team conducts research and analysis to understand where, how and who might be vulnerable to various emergencies and crises within the UK.                  

**Could you elaborate on the types of sessions and workshops available and how they cater to different interests and skill levels within the R community?**

The day will consist of eight 25-ish minute talks, plus Q&A, from a variety of speakers across various sectors. 

The talks are on a wide range of topics. For example, last year we had speakers talking about everything from using R for mapping air quality, to EDI and sustainability in the R project, and why R is good for data journalism. If you want to take a look at what you can expect, we have a ~~[playlist of last year’s talk recordings](https://youtube.com/playlist?list=PLbARZQfpqIKLNjt5NnVQ1RgEKeayVVv6G&si=qlaeJm8GN9opZqFC)~~ available on our YouTube channel.

**With the event being hosted at King’s College London, how does the venue enhance the experience for attendees, both in terms of facilities and location?**

We’re very excited to be partnering with [CUSP London](https://cusplondon.ac.uk/) again this year, who provide the amazing Bush House venue at King’s College London. The venue is a beautiful listed building, right in the heart of London, only a few minutes walk from Covent Garden. 

Being in the center of London means easy access to multiple public transport links, both for national and international attendees!

The venue facilities and supporting technology provides a great space for sharing insights and networking.


### [Don’t miss out, register today!](https://satrdays-london-2024.jumpingrivers.com/#registration)