---
title: "R/Medicine is coming June 10-14, 2024 – See Top Five R Medicine Talks from Previous Years"
description: "What to get a feel for the kind of content will be available at R/Medicine 2024?"
author: "R Consortium"
date: "04/30/2024"
---
What to get a feel for the kind of content will be available at [R/Medicine 2024](https://rconsortium.github.io/RMedicine_website/)? We’re spotlighting the most engaging and educational sessions from past R Medicine Virtual Conferences. Whether you’re a healthcare professional, a data scientist, or simply curious about the intersection of healthcare and technology, these selected talks offer a wealth of knowledge and innovation using the R programming language. Dive into these sessions to enhance your understanding and skills in medical data science.

### [🔗 Register for the R Medicine 2024 Virtual Conference here!](https://rconsortium.github.io/RMedicine_website/)

### 1\. GitHub Copilot in Rstudio, It’s Finally Here! – R Medicine Virtual Conference 2023

This session introduces GitHub Copilot for RStudio, a highly anticipated tool that enhances coding efficiency and innovation in medical research. Watch as experts demonstrate its capabilities and potential impact on healthcare data analysis.

<iframe title="GitHub Copilot in Rstudio, it's finally here!" src="https://www.youtube.com/embed/yVq-b5xHmac?feature=oembed&amp;enablejsapi=1&amp;origin=https://www.r-consortium.org" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen="" data-aspectratio="0.56"></iframe>

### 2\. Analyzing Geospatial Data in R (Sherrie Xie) – R/Medicine 2022 Virtual Conference

Featuring Sherrie Xie, this presentation explores the applications of geospatial data analysis within the healthcare sector using R. Gain insights into the importance of spatial data in understanding health trends and outcomes.

<iframe title="Analyzing Geospatial Data in R (Sherrie Xie)" src="https://www.youtube.com/embed/DD7bXonh-_E?feature=oembed&amp;enablejsapi=1&amp;origin=https://www.r-consortium.org" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen="" data-aspectratio="0.56"></iframe>

### 3\. R/Medicine 101: Intro to R for Clinical Data (Stephan Kadauke, Joe Rudolf, Patrick Mathias) – R/Medicine 2022

This introductory session is perfect for those new to using R in a clinical setting. The speakers guide you through the basics and demonstrate how R can revolutionize medical research and patient care.

<iframe title="R/Medicine 101: Intro to R for Clinical Data (Stephan Kadauke, Joe Rudolf, Patrick Mathias)" src="https://www.youtube.com/embed/jTf_N5zX5wY?list=PL4IzsxWztPdmSeucR67EH_8_hzldqYZX4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen="" data-aspectratio="0.56"></iframe>

### 4\. Introduction to R for Medical DataTidy Spreadsheets in Medical Research – R/Medicine 2021

UMich Prof and {medicaldata} author Peter Higgins will cover best practices for using medical data in spreadsheets like Excel and Google Sheets.

<iframe loading="lazy" title="Tidy Spreadsheets in Medical Research - Peter Higgins - R/Medicine Workshop - 2021-02-23" src="https://www.youtube.com/embed/9f-hpJbjKZo?list=PL4IzsxWztPdnzvOQMrwkNI0payDVmmwse" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen="" data-aspectratio="0.56"></iframe>

### 5\. Multistate Data Using the {survival} Package – R/Medicine 2021

Explore the use of the {survival} package in R for analyzing multistate data. Discover the methods and models that are shaping the future of survival analysis in medical research.

<iframe loading="lazy" title="Multistate Data Using the {survival} Package" src="https://www.youtube.com/embed/xD4j8Rxm2vo?list=PL4IzsxWztPdmHxCpS_c2l_jbMfrywWciZ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen="" data-aspectratio="0.56"></iframe>

Engage and Learn More!

Each of these sessions provides unique insights and practical tools for harnessing the power of R in medical research and healthcare analytics. Whether you are watching these for the first time or revisiting them, each video promises a deep dive into the capabilities of R that are driving advancements in the field.

📢 Mark Your Calendars! The R Medicine Conference for this year is scheduled for June 10-14. Register now to secure your spot and connect with a community of like-minded professionals!

### [🔗 Register for the R Medicine 2024 Virtual Conference here!](https://rconsortium.github.io/RMedicine_website/)

Remember to subscribe to the R Medicine channel for more updates and upcoming conference information. Enhance your skills in medical data science today!

