
# FAQ



* [Is the R Consortium committed to R as an open-source project?](https://www.r-consortium.org/faq#1)
* [Do I have to be an employee of a member of the R Consortium to contribute to infrastructure projects?](https://www.r-consortium.org/faq#2)
* [Was the R community consulted about the projects considered by the R Consortium?](https://www.r-consortium.org/faq#3)
* [What kinds of projects will the R Consortium undertake?](https://www.r-consortium.org/faq#4)
* [How are R Consortium projects selected and managed?](https://www.r-consortium.org/faq#5)
* [Are the leaders of the R Consortium R users?](https://www.r-consortium.org/faq#6)
* [Can I review the governance documents for the R Consortium?](https://www.r-consortium.org/faq#7)
* [How is the R Consortium governed?](https://www.r-consortium.org/faq#8)
* [Are membership dues tax-deductible?](https://www.r-consortium.org/faq#9)
* [Can an individual become a member of the R Consortium?](https://www.r-consortium.org/faq#10)
* [Why the focus on organizations rather than individuals?](https://www.r-consortium.org/faq#11)
* [What is the relationship between the R Consortium and the Linux Foundation?](https://www.r-consortium.org/faq#12)
* [What is the relationship between the R Consortium and the R Foundation?](https://www.r-consortium.org/faq#13)
* [Who are the members of the R Consortium?](https://www.r-consortium.org/faq#14)
* [Why an R Consortium?](https://www.r-consortium.org/faq#15)
* [Do I have to be an employee of a member of the R Consortium to contribute to infrastructure projects?](https://www.r-consortium.org/faq#16)
* [Can I review the governance documents for the R Consortium?](https://www.r-consortium.org/faq#17)
* [What wouldn’t the R Consortium do?](https://www.r-consortium.org/faq#18)
* [What kinds of projects will the R Consortium undertake?](https://www.r-consortium.org/faq#19)
* [Who will be involved?](https://www.r-consortium.org/faq#20)

 


Is the R Consortium committed to R as an open-source project?


Definitely! The R Consortium’s explicit mission is to “advance the worldwide promotion of and support for the R open source language”, and all of its activities are in support of the Open Source R Project. It will support and promote the use of Open Source R in all contents, including in commercial and business settings.


As defined in its ~~[charter](https://www.r-consortium.org/isc-charter.r-consortium.org)~~, the projects of the Infrastructure Steering Committee will focus on support of the user base, support of developers, and general advancement of Open Source R. In particular, a commercial fork of R isn’t compatible with that mission, and won’t be a project of the R Consortium.

* [Back to Top](https://www.r-consortium.org/faq#top)

Do I have to be an employee of a member of the R Consortium to contribute to infrastructure projects?


No. The R Consortium [welcomes contributions of time, effort and ideas](https://www.r-consortium.org/all-projects/call-for-proposals) for all passionate users and developers of the R language.

* [Back to Top](https://www.r-consortium.org/faq#top)

Was the R community consulted about the projects considered by the R Consortium?


Yes. R Consortium projects are [proposed by the community to the Infrastructure Steering Committee](https://www.r-consortium.org/all-projects).

* [Back to Top](https://www.r-consortium.org/faq#top)

What kinds of projects will the R Consortium undertake?


The R Consortium will coordinate and support projects that directly benefit stakeholders within the R user community. Here are some examples of the types of projects the R Consortium might undertake

* Improving documentation and tools.
* Sponsoring and helping execute  conferences and events.
* Helping to scale and build out R infrastructure.
* Maintaining an enhanced website focused on the R user community.

This is not an exhaustive list. Anyone may ~~[propose a project](https://www.r-consortium.org/all-projects/submit-proposal)~~ to the Infrastructure Steering Committee, which selects and executes projects.

* [Back to Top](https://www.r-consortium.org/faq#top)

How are R Consortium projects selected and managed?


The technical projects undertaken by the R Consortium in support of the R Project and the R Community are overseen by the [Infrastructure Steering Committee](https://www.r-consortium.org/all-projects). The ~~[charter of the Infrastructure Steering Committee](https://www.r-consortium.org/isc-charter.r-consortium.org)~~ (ISC) describes its mission, which is to advance the worldwide promotion of and support for R, and to develop projects, technical and infrastructure collaboration initiatives, support specific initiatives related to R. The membership of the ISC is drawn from the Platinum Members, Silver Members and the R Foundation. As the ISC appoints top-level projects, it is expected that those project leads will join the ISC as voting members.

* [Back to Top](https://www.r-consortium.org/faq#top)

Are the leaders of the R Consortium R users?


The Board Members (including the Chairperson) are appointed or elected by members (depending on the membership class). There is always one board member representing the R Foundation, to provide guidance to the R Consortium in its mission to support the R Project. The remaining Board members are drawn from the membership, and represent the organizations that have joined the R Consortium. All of the [current board members](https://www.r-consortium.org/about/governance) have extensive R experience.


The [members of the Infrastructure Steering Committee](https://www.r-consortium.org/all-projects) are appointed by the Platinum Members, Silver Members, and the R Foundation member, and includes representatives with significant technical experience, including R package developers, community leaders, and the individuals from the R Core Group.

* [Back to Top](https://www.r-consortium.org/faq#top)

Can I review the governance documents for the R Consortium?


Yes! You can review the [by-laws for the R Consortium, Inc.](https://www.r-consortium.org/wp-content/uploads/sites/13/2019/11/R-Consortium-Bylaws-1157174-v2-Approved-11.20.19.pdf) and the ~~[charter for the Infrastructure Steering Committee](https://www.r-consortium.org/isc-charter.r-consortium.org)~~.

* [Back to Top](https://www.r-consortium.org/faq#top)

How is the R Consortium governed?


The R Consortium is governed by the R Consortium Board of Directors, which is made up of representatives determined by its members. (Members of the board are elected or appointed depending on membership levels; for details please see the [by-laws](https://www.r-consortium.org/wp-content/uploads/sites/13/2019/11/R-Consortium-Bylaws-1157174-v2-Approved-11.20.19.pdf).) The Board meets regularly to manage the business of the Consortium. Meetings are led by the Chairperson of the R Consortium, a rotating position held by a board member elected by the Board as a whole.


The technical projects undertaken by the R Consortium in support of the R Project and the R Community are overseen by the [Infrastructure Steering Committee](https://www.r-consortium.org/all-projects).

* [Back to Top](https://www.r-consortium.org/faq#top)

Are membership dues tax-deductible?


The R Consortium is a US-based 501(c)6 non-profit organization. Dues are not tax-deductible as charitable donations by individuals, but under [US IRS rules](https://www.r-consortium.org/bylaws.r-consortium.org) may be deductible as trade or business expenses.

* ~~[Back to Top](https://www.r-consortium.org/faq-page#faq-top)~~

Can an individual become a member of the R Consortium?


Yes, individuals may support the R Consortium by joining as a non-voting associate member. You can also support the R project by [contributing to the R Foundation](https://www.r-consortium.org/about/join) directly.

* [Back to Top](https://www.r-consortium.org/faq#top)

Why the focus on organizations rather than individuals?


Hundreds of companies around the world have invested heavily in R, by building systems on the R platform and by hiring thousands of R developers. The R Consortium provides a means for those companies to invest in the R Project directly, to collaborate on projects of mutual interest to support the R Community as a whole, and to support the ongoing success of the R Project.

* [Back to Top](https://www.r-consortium.org/faq#top)

What is the relationship between the R Consortium and the Linux Foundation?


The R Consortium is an independent organization, but as [Collaborative Project of the Linux Foundation](http://collabprojects.linuxfoundation.org/?__hstc=98577409.44d7f16716270a3b9b81de6d864e02dc.1720553161514.1720553161514.1720553161514.1&__hssc=98577409.10.1720553161514&__hsfp=1019891917), the Linux Foundation provides operational support and guidance.

* [Back to Top](https://www.r-consortium.org/faq#top)

What is the relationship between the R Consortium and the R Foundation?


The [R Foundation](https://www.r-project.org/foundation/) is the leader of the R Project and the custodian of the R source code and copyright. The R Foundation determines the definition and evolution of the R language.


The R Consortium, as an independent entity, exists to support the R Community and the R Project as a whole — and that includes providing support to the R Foundation. That’s why the R Foundation has a guaranteed seat on the Board and the Infrastructure Steering Committee, to represent the interests of the R Foundation and to propose projects to support R itself.

* [Back to Top](https://www.r-consortium.org/faq#top)

Who are the members of the R Consortium?


Members of the R Consortium include the [following types of organizations](https://www.r-consortium.org/bylaws.r-consortium.org): any association, partnership, organization, governmental agency, company, corporation, academic entity, or non-profit entity with an interest in supporting R. (Individuals may also join as associate members.) In addition, the [R Foundation](https://www.r-project.org/foundation/) is automatically a member and always has a seat on the Board and the Infrastructure Steering Committee. You can see a [current list of members here](https://www.r-consortium.org/about/governance).

* [Back to Top](https://www.r-consortium.org/faq#top)

Why an R Consortium?


The R user community has experienced tremendous growth.  With growth there is a greater need for cooperation and communication among R users and R stakeholders.  R will continually benefit from improvements to its technical tools and resources.  The [mission of the R Consortium](https://www.r-consortium.org/about) is to help with support and coordination of the important activities of the R Community, via projects selected and executed its [Infrastructure Steering Committee](https://www.r-consortium.org/all-projects).

* [Back to Top](https://www.r-consortium.org/faq#top)

Do I have to be an employee of a member of the R Consortium to contribute to infrastructure projects?


No! The R Consortium welcomes contributions of time, effort and ideas for all passionate users and developers of the R language. After formal meetings of the Infrastructure Steering Committee have begun (which we anticipate will occur soon), we will distribute information on how project ideas can be submitted to the Infrastructure Steering Committee.

* [Back to Top](https://www.r-consortium.org/faq#top)

Can I review the governance documents for the R Consortium?


Yes! You can find copies of the [by-laws](https://www.r-consortium.org/wp-content/uploads/sites/13/2019/11/R-Consortium-Bylaws-1157174-v2-Approved-11.20.19.pdf) for the R Consortium, Inc. and the charter for the infrastructure steering committee.

* [Back to Top](https://www.r-consortium.org/faq#top)

What wouldn’t the R Consortium do?


Interfere with the R language itself and its development.

* [Back to Top](https://www.r-consortium.org/faq#top)

What kinds of projects will the R Consortium undertake?


The R Consortium will coordinate and support projects that directly benefit stakeholders within the R user community, for example:

*  Improving documentation and tools.
* Sponsoring and helping execute  conferences and events.
* Helping to scale and build out R infrastructure.
* Maintaining an enhanced website focused on the R user community.
* [Back to Top](https://www.r-consortium.org/faq#top)

Who is involved?


R users and stakeholders as members of the consortium in addition to representatives from the R Foundation with operational support provided by The Linux Foundation.

* [Back to Top](https://www.r-consortium.org/faq#top)