# About

The R Consortium, Inc. is a group organized under an open source governance and foundation model to support the worldwide community of users, maintainers and developers of R software. Its [members](../members.qmd) include leading institutions and companies dedicated to the use, development and growth of R.

The R language is an open source environment for statistical computing and graphics. The R community has enjoyed significant growth, with more than 2 million users worldwide. A broad range of organizations have adopted the R language as a data science platform, including biotech, finance, research and high technology industries. The R language is often integrated into third-party analysis, visualization and reporting applications, and runs on a wide variety of computing platforms.

The R Consortium’s mission is to promote the R language and to develop the technical and social infrastructure required to support the R ecosystem and the R Community. Its activities and programs include:

  * Promoting the growth and development of R as a leading platform for data science and statistical computing.
      * [Members of the R Consortium](../members.qmd) are recognized as supporters of the R Project and the R community, and the R Consortium represents its members to the R community and to the media.
  * Supporting and collaborating with the [R Foundation](https://www.r-project.org/foundation/), the governing body of the R Project.
      * The R Foundation maintains a permanent seat on the board of the R Consortium, as an open communication channel for R Consortium members.
  * Funding projects to enhance R and support its users.
      * Projects are proposed by the R community at large, and selected for funding by the Infrastructure Steering Committee. R Consortium members nominate the selection committee and provide funds for project grants with their membership dues. (Here is a list of [projects funded by the R Consortium](../all-projects/funded-projects.qmd) to date.)
  * Fostering the continued growth of R community and the data science ecosystem.
      * The R Consortium sponsors R-related conferences (including useR!), meetings (including SatRDays and RLadies), and local user groups worldwide.
* Enabling the use of R in commercial environments, and fostering collaboration between companies investing in R.
    * R Consortium committees are developing programs for R language certification and training, consulting, and employment.

The mission of the R Consortium is formally defined in the [R Consortium bylaws](../docs/Bylaws-GU-Draft-7-9-2024.docx.pdf) and the [Infrastructure Steering Committee charter](../docs/ISC-Charter-08-11-23.pdf).


### What is R?

R is an open source language and environment for statistical computing and graphics.
