# Why Join the R Consortium?

The R Consortium is the mechanism for corporate entities and other organizations to support  and engage with the R Community. Membership in the R Consortium signals community leadership, a long term viewpoint, and an appreciation for the efforts of R’s open source contributors. Membership shows commitment and a desire to contribute to the community, strengthening it for the benefit of all.

## Membership in the R Consortium

-   Helps fund key R infrastructure such as the R-Hub build system, database interfaces, distributed computing architecture, regional conferences, local R user groups and more.
-   Provides a way for companies to generate industry-wide support for projects that they see as valuable.
    -   The bulk of the R Consortium budget goes directly to funding key community projects.
-   Through participation in the R Consortium Infrastructure Steering Committee (ISC), members have a voice in the process of selecting projects and the opportunity to guide their development.
-   Gives companies direct access to the R Foundation:
    -   Board members interact with the R Foundation’s representative on the R Consortium Board of Directors.
    -   ISC members:
        -   Work side-by-side with R Foundation members engaged in technical projects,
        -   Participate in regular meetings with R Foundation members.
-   Provides insight and access to accurate and up-to-date knowledge about important developments in the the R Community and the extended R ecosystem.

## How R Consortium membership helps support the R Community

-   Supports the operations of the critical infrastructure that sustains the R ecosystem, anticipating challenges and planning for contingencies.  
-   Funds open-source community-driven projects that widely impact the R Community
-   Provides opportunities to form working relationships that transcend company affiliations.
-   Enables better identification and recruitment of data scientists working in R.
-   Convenes thought leadership events, summits, and panels among subject matter experts to discuss technology, standards, specifications, best practices, and collaboration


<table><tbody><tr><td><h5><strong>Benefits by member class</strong></h5></td><td><h5><strong>Platinum</strong></h5></td><td><h5><strong>Silver</strong></h5></td><td></td></tr><tr><td><span>One seat on the Board of Directors with full voting rights</span></td><td><pre><span>X</span></pre></td><td></td><td></td></tr><tr><td><span>One seat on the ISC with full voting rights &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></td><td><pre><span>X</span></pre></td><td></td><td></td></tr><tr><td><span>Elect Silver representatives to the Board and ISC ( 1 Board seat per 3 Silver members, 1 ISC seat for all Silver members )</span></td><td></td><td><pre><span>X</span></pre></td><td></td></tr><tr><td><span>Company logo on R Consortium website and collateral</span></td><td><pre><span>X</span></pre></td><td><pre><span>X</span></pre></td><td></td></tr><tr><td><span>R Consortium logo on company website</span></td><td><pre><span>X</span></pre></td><td><pre><span>X</span></pre></td><td></td></tr><tr><td><span>Membership dues ( annually )</span></td><td><p><span>US$100,000</span></p></td><td><p><span>100+ FTE US $25,000</span></p><p><span>&lt;100 FTE / non-profits, universities US $10,000</span></p></td><td></td></tr><tr><td></td><td></td><td></td><td></td></tr></tbody></table>

### Joining the R Consortium is easy.

1. Review the Membership Documents.

-   [R Consortium Membership Datasheet](../rc-docs/r_consortium_datasheet.pdf)
-   [R Consortium Bylaws](../rc-docs/Bylaws-GU-Draft-7-9-2024.docx.pdf)
-   [R Consortium Membership Agreement](../rc-docs/R-Consortium-Membership-Agreement-1157181-v2-Approved-11.20.19.pdf)
-   [R Consortium – Certificate of Incorporation](../rc-docs/R-Consortium-Certificate-of-Incorporation.pdf)

2. Fill out our online [membership application form](https://join.r-consortium.org/).

3. Remit the annual dues payment that is applicable for your membership level.

4. Begin participating in Events, Discussions, Projects and working Groups.

If you have questions about membership or joining the R Consortium, please contact our [member support desk](https://members.r-consortium.org/) and you will be contacted as soon as possible. Thank you.

```{.r}
#| echo: false
#| warning: false
#| message: false

library(lubridate)
library(gt)
# For every day of the conference, have data laid out in this way
schedule_day_1 <-
  dplyr::tribble(
    ~start_time, ~end_time, ~t_number, ~t_type, ~t_title, ~t_speakers, ~t_speaker_titles, ~t_companies,
    "2024-06-10 11:00", "2024-06-10 14:00", "1A", "Workshop", "Causal Inference in R", "Travis Gerke", "Director of Data Science", "Prostate Cancer Clinical Trials Consortium",
    "2024-06-10 11:00", "2024-06-10 14:00", "1B", "Workshop", "Promover la Equidad Científica: Una Introducción al uso de R para la programación en Bioestadística y Ciencia de Datos, en Español", "Catalina Canizares-Escobar, Francisco Cardozo", "Study Coordinator, PhD student", "Florida International University",
    "2024-06-10 14:00", "2024-06-10 14:30",  NA, "Break", NA, NA, NA, NA,
    "2024-06-10 14:30", "2024-06-10 17:30", "2A", "Workshop", "Google BigQuery: First Steps in R", "Joy Payton", "Data Scientist", "CHOP",
    "2024-06-10 14:30", "2024-06-10 17:30", "2B", "Workshop", "Project Oriented Workflows", "Shannon Pileggi", "Data Scientist", "Prostate Cancer Clinical Trials Consortium",
    "2024-06-10 17:30", "2024-06-10 20:30", "3A", "Workshop", "Tidy time series analysis and forecasting", "Mitchell O'Hara-Wild", "Data Scientist", "Nectric"
  ) |>
  dplyr::mutate(duration = time_length(ymd_hm(end_time) - ymd_hm(start_time), unit = "mins"))
```

```{r}

# Create a table for the day of events
gt(schedule_day_1) |>
  tab_header(title = md("<br>Workshop Day 1<br>Monday, June 10, 2024.<br>All Times EST<br><br>")) |> # <- insert the date
  fmt_time(columns = c(start_time, end_time), time_style = "h_m_p") |>
  fmt_duration(
    columns = duration,
    input_units = "minutes",
    output_units = c("hours", "minutes")
  ) |>
  cols_move(columns = duration, after = end_time) |>
  cols_merge(
    columns = c(t_number, t_type, t_title, t_speakers, t_speaker_titles, t_companies),
    pattern = md("<<{1} - >>{2}<br><< {3}<br>{4}<br>{5}, {6}>>")
  ) |>
  cols_label(
    start_time ~ "Start Time",
    end_time ~ "End Time",
    duration ~ "Duration",
    t_number ~ ""
  ) |>
  cols_align(align = "center") |>
  cols_width(
    c(start_time, end_time, duration) ~ px(90),
    everything() ~ px(600)
  ) |>
  opt_align_table_header(align = "left") |>
  tab_options(
    heading.background.color = "lightblue",
    column_labels.background.color = "gray85"
  ) |>
  tab_style(
    locations = cells_body(rows = t_type == "Break"),
    style = cell_fill(color = "bisque")
  )

```