# Contributors to this Website

The R language is open source and is supported worldwide by people who are enthusiastic to learn and improve. The R Consortium supports R infrastructure technology projects, events, webinars, R user groups, and much more. We support the R community and we benefit from it, too.

## The following people have helped contribute to this R Consortium quarto-based website:

Simisani Ndaba, R-Ladies Gaborone chapter founder and organizer

Isabella Velásquez, Sr. Product Marketing Manager, Posit

Erik Rodriguez, San Jose State University, Information Science & Data Analytics major

Phat Ca, University of Hawaii, Computer Science major

Priyanka Gagneja, R-Ladies Gaborone member

Daniel D. Sjoberg (he/him) is a Software Engineer at Genentech, contributed R plot to main homepage. Webinar talk here: [https://www.r-consortium.org/r-medicine-webinar-visualizing-survival-data-with-the-ggsurvfit-r-package]()

Christoph Scheuch is the Head of Artificial Intelligence at the social trading platform wikifolio Financial Technologies AG, contributed R plot to main homepage. Previous webinar here: [https://www.r-consortium.org/new-webinar-tidy-finance-and-accessing-financial-data Upcoming webinar series here: https://www.r-consortium.org/tidy-finance-webinar-series]()