---
title: Elevate Your R Community with the 2024 RUGS Grant Program
description: "The R Consortium is rolling out its 2024 R User Groups (RUGS) Grant Program, and it's an opportunity you don't want to miss. The program, which aims to foster vibrant…"
author: "R Consortium"
image: ""
date: "03/26/2024"
format: html
---
<style>
  .anchorjs-link {
  display: none !important;
}
</style>
The R Consortium is rolling out its 2024 R User Groups (RUGS) Grant Program, and it’s an opportunity you don’t want to miss. The program, which aims to foster vibrant R communities worldwide, is in full swing, and we are eagerly awaiting your application!


### [Apply here!](https://www.r-consortium.org/all-projects/r-user-group-support-program)


# **Why Apply and… For What?**

**User Group Grants:** Boost engagement and initiate user-focused activities.

**Conference Grants:** Support for R-related events, either hosting or attending.

**Special Projects Grants:** Kickstart innovative projects with the potential to impact the R community.

With 74 active groups and a thriving community of over 67,000 members, the RUGS network is a hub of innovation and knowledge sharing. Your participation could be the next milestone in this growth journey.

Examples of some recent R Consortium sponsored RUGS activities:



* [The Cleveland R User Group’s Journey Through Pandemic Adaptations and Baseball Analytics](https://www.r-consortium.org/blog/2024/03/07/the-cleveland-r-user-groups-journey-through-pandemic-adaptations-and-baseball-analytics)
* [R-Ladies Goiânia: Promoting Diversity and Inclusion in Local R Community](https://www.r-consortium.org/blog/2024/03/13/r-ladies-goiania-promoting-diversity-and-inclusion-in-local-r-community)


# **Key Information**

**Application Deadline:** September 30th, 2024. Don’t delay!

**Eligibility:** Open to initiatives aimed at community building, not software development (for that, see [ISC Grant Program](https://www.r-consortium.org/all-projects/call-for-proposals)).

**Be part of shaping the future of R.** Visit here for more details and to apply. Your contribution matters to the global R narrative. Apply now, and let’s grow together!


### For details and to apply, [visit here](https://www.r-consortium.org/all-projects/r-user-group-support-program).




