[Want to contribute to the R Consortium blog? Please review our Blog Post Guidelines.](https://www.r-consortium.org/news/blog/guidelines)


### [Kolkata R User Group: A Rich History with Statistics ](../posts/kolkata-r-user-group-a-rich-history-with-statistics)

The R Consortium recently spoke with Samrit Pramanik of the Kolkata R User Group about his experience starting a new R User Group in India. Samrit highlighted Kolkata's rich history…


### [Diving into R with Isabella Velasquez: Perspectives from R-Ladies Seattle](../posts/diving-into-r-with-isabella-velasquez-perspectives-from-r-ladies-seattle/)

Isabella Velasquez, co-organizer of R-Ladies Seattle, recently spoke with the R Consortium about her journey with R and the group’s recent activities. Isabella started as a beginner but has become…


### [R Consortium’s Submission Working Group: Advancing R for Regulatory Success at PharmaSUG 2024](../posts/r-consortiums-submission-working-group-advancing-r-for-regulatory-success-at-pharmasug-2024)

The R Submission Working Group is making significant strides in promoting the use of R for regulatory submissions in the pharmaceutical industry. At PharmaSUG 2024, held from May 19-22 in…


### [R Addicts Paris: Promoting Diversity in R](../posts/r-addicts-paris-promoting-diversity-in-r)

Vincent Guyader, organizer of the R Addicts Paris and president of ThinkR, recently updated the R Consortium on the group's activities. Last year, Vincent discussed the application of R in…


### [The Crucial Role of Release Control in R for Healthcare Organizations](../posts/the-crucial-role-of-release-control-in-r-for-healthcare-organizations)

Guest blog contributed by Ning Leng, People and Product Leader, Roche-Genentech. Eric Nantz, Director, Eli Lilly and Company; Ben Straub, Principal Programmer, GSK; Sam Parmar, Statistical Data Scientist, Pfizer.  Supporting the science of drug development requires computational tools with careful implementations of core statistical functions and data structures...


### [Bridging the Digital Divide: Umar Isah Adam on Expanding R Access for Kano, Nigeria Students](https://www.r-consortium.org/blog/2024/06/17/bridging-the-digital-divide-umar-isah-adam-on-expanding-r-access-for-kano-nigeria-students) [ARCHIVE]

Umar Isah Adam, the founder and organizer of the R User Group Kano, Nigeria, spoke with the R Consortium during the pandemic about his efforts to engage the next generation…


### [Keith Karani Wachira: Leading the Dekut R Community in Kenya and Innovating with R ](https://www.r-consortium.org/blog/2024/06/11/keith-karani-wachira-leading-the-dekut-r-community-in-kenya-and-innovating-with-r) [ARCHIVE]

Keith Karani Wachira, the Dekut R Community organizer based in Nyeri, Kenya, was recently interviewed by the R Consortium and shared his journey in the R community, which began in…


### [Full-time Korea R User Group Founder Victor Lee Sees AI Future for R and Quarto Textbooks](../posts/Full-time-Korea-R-User-Group-Founder-Victor-Lee-Sees-AI-Future-for-R-and-Quarto-Textbooks-R-Consortium)

The R Consortium recently interviewed Victor Lee, organizer of the Korea R User Group, about his role establishing and expanding the Korean R community. Victor shared his journey, beginning with…


### [R4HR in Buenos Aires: Leveraging R for Dynamic HR Solutions](https://www.r-consortium.org/blog/2024/05/30/r4hr-in-buenos-aires-leveraging-r-for-dynamic-hr-solutions) [ARCHIVE]

Marcela Victoria Soto, co-organizer of the R4HR -Club de R para RRHH, Buenos Aires, Argentina, recently updated the R Consortium about the group’s recent activities. Last year, Sergio García Mora,…


### [One More Step Forward: The R Consortium Submission Working Group’s Presentation to Swissmedic on Regulatory Submission using R and Shiny](https://www.r-consortium.org/blog/2024/05/29/one-more-step-forward-the-r-consortium-submission-working-groups-presentation-to-swissmedic-on-regulatory-submission-using-r-and-shiny) [ARCHIVE]

This post was authored by Gregory Chen, Biostatistics and Research Decision Sciences (BARDS), MSD, Switzerland, and Ning Leng, Product Development Data Sciences (PDD), F. Hoffmann-La Roche, USA On January 30,…


### [Collaborative Growth: The Botswana R User Group and Regional Partnerships](https://www.r-consortium.org/blog/2024/05/24/collaborative-growth-the-botswana-r-user-group-and-regional-partnerships) [ARCHIVE]

Last year, Edson Kambeu, founder and organizer of the Botswana R User Group, shared his plans with the R Consortium to implement data into local businesses in the New R…


### [Gergely Daróczi’s Journey: Empowering R Users in Hungary](https://www.r-consortium.org/blog/2024/05/16/gergely-daroczis-journey-empowering-r-users-in-hungary) [ARCHIVE]

Gergely Daróczi, the founder and organizer of the Budapest Users of R Network, updated the R Consortium about the group’s recent activities. Last year, Gergely discussed the group's inception, and…


### [Enhancing R: The Vision and Impact of Jan Vitek’s MaintainR Initiative](https://www.r-consortium.org/blog/2024/05/15/enhancing-r-the-vision-and-impact-of-jan-viteks-maintainr-initiative) [ARCHIVE]

The R Consortium recently interviewed Jan Vitek, a professor at Northeastern University's Khoury College of Computer Sciences. He specializes in programming languages, compilers, and systems. Notably, he developed one of…


### [Tackling Hurdles: Embracing Open Source Packages in Pharmaceutical Research](https://www.r-consortium.org/blog/2024/05/14/tackling-hurdles-embracing-open-source-packages-in-pharmaceutical-research) [ARCHIVE]

The R Validation Hub next meeting is May 21st, 12:00 PM EST.  Join the call here!  In the dynamic field of pharmaceutical research, open source R packages offer incredible potential…


### [The Evolution of Melbourne’s Business Analytics and R Business User Group ](https://www.r-consortium.org/blog/2024/05/13/the-evolution-of-melbournes-business-analytics-and-r-business-user-group) [ARCHIVE]

Maria Prokofieva, organizer of the Business Analytics and R Business User Group, spoke to the R Consortium last year about the Adoption of R by the Actuaries Community in Melbourne.…


### [R/Medicine is coming June 10-14, 2024 – See Top Five R Medicine Talks from Previous Years](https://www.r-consortium.org/blog/2024/04/30/r-medicine-is-coming-june-10-14-2024-see-top-five-r-medicine-talks-from-previous-years) [ARCHIVE]

What to get a feel for the kind of content will be available at R/Medicine 2024? We’re spotlighting the most engaging and educational sessions from past R Medicine Virtual Conferences.…


### [Enhancing Clinical Trial Data Sharing with R Consortium’s R Submissions Working Group](https://www.r-consortium.org/blog/2024/04/29/enhancing-clinical-trial-data-sharing-with-r-consortiums-r-submissions-working-group) [ARCHIVE]

The R Consortium's working group R Submissions Working Group is spearheading an innovative approach to clinical trial data sharing, according to a feature in Nature. This initiative, led by Eric…


### [Bridging Gaps: Tunis R User Group’s Journey in Democratizing R in Bioinformatics](https://www.r-consortium.org/blog/2024/04/26/bridging-gaps-tunis-r-user-groups-journey-in-democratizing-r-in-bioinformatics) [ARCHIVE]

Last year, the R Consortium had a conversation with Amal Tlili, the co-organizer of the Tunis R User Group, regarding the Use of R for Marketing and CRM in Tunisia.…


### [Navigating R’s Impact in Vienna: Insights from the Finance and Pharmaceutical Sectors](https://www.r-consortium.org/blog/2024/04/19/navigating-rs-impact-in-vienna-insights-from-the-finance-and-pharmaceutical-sectors) [ARCHIVE]

The R Consortium recently spoke with Mario Annau, co-organizer of the Vienna R User Group. During the conversation, he discussed the use of R in the finance and pharmaceutical industries…


### [Building Data Highways: Kirill Müller’s Journey in Enhancing R’s Database](https://www.r-consortium.org/blog/2024/04/18/building-data-highways-kirill-mullers-journey-in-enhancing-rs-database) [ARCHIVE]

Kirill Müller is the author of the {DBI} package, which helps to connect R and database management systems (DBMS). The connection to a DBMS is achieved through database-specific backend packages…


### [Decade of Data: Celebrating 10 Years of Innovation at the New York R Conference](https://www.r-consortium.org/blog/2024/04/15/decade-of-data-celebrating-10-years-of-innovation-at-the-new-york-r-conference) [ARCHIVE]

Come celebrate 10 YEARS of the New York R Conference! This year's conference takes place May 16th & 17th with workshops May 15th. We are taking a trip down memory…


### [The Impact of R on Academic Excellence in Manchester, UK](https://www.r-consortium.org/blog/2024/04/10/the-impact-of-r-on-academic-excellence-in-manchester-uk) [ARCHIVE]

The R Consortium recently spoke with the organizing team of the R User Group at the University of Manchester (R.U.M.). R.U.M. aims to bring together R users of all levels…


### [EARL Early Bird Tickets Are Now Available!](https://www.r-consortium.org/blog/2024/04/08/earl-early-bird-tickets-are-now-available) [ARCHIVE]

Contributed by Abbie Brookes, Senior Data Analyst at Datacove Datacove is pleased to announce the availability of tickets for the upcoming EARL (Enterprise Applications of the R Language) conference.  The…


### [R/Medicine Coming June 10-14, 2024 – Call for Abstracts Open – Keynotes Announced](https://www.r-consortium.org/events/2024/04/05/r-medicine-coming-june-10-14-2024) [ARCHIVE]

The R/Medicine conference provides a forum for sharing R based tools and approaches used to analyze and gain insights from health data. Conference workshops provide a way to learn and…


### [Unlocking Financial Insights: Join Us at the R Finance Conference](https://www.r-consortium.org/blog/2024/04/04/unlocking-financial-insights-join-us-at-the-r-finance-conference) [ARCHIVE]

Are you ready to delve into the world of finance through the lens of R? Look no further than the R Finance Conference (May 18, 2024,  University of Illinois Chicago)…


### [Empowering R Enthusiasts: SatRDays London 2024 Unveiled](https://www.r-consortium.org/blog/2024/03/28/empowering-r-enthusiasts-satrdays-london-2024-unveiled) [ARCHIVE]

SatRDays London 2024 is set to ignite the data science community with a vibrant lineup of speakers and a rich array of topics ranging from survival analysis to geospatial data.…


### [Aligning Beliefs and Profession: Using R in Protecting the Penobscot Nation’s Traditional Lifeways](https://www.r-consortium.org/blog/2024/03/27/aligning-beliefs-and-profession-using-r-in-protecting-the-penobscot-nations-traditional-lifeways) [ARCHIVE]

Angie Reed sampling Chlorophyll on the Penobscot River where a dam was removed  In a recent interview by the R Consortium, Angie Reed, Water Resources Planner for the Penobscot Indian…


### [Elevate Your R Community with the 2024 RUGS Grant Program](https://www.r-consortium.org/blog/2024/03/26/elevate-your-r-community-with-the-2024-rugs-grant-program) [ARCHIVE]

The R Consortium is rolling out its 2024 R User Groups (RUGS) Grant Program, and it's an opportunity you don't want to miss. The program, which aims to foster vibrant…


### [Offa R Users Group: Empowering Data-Driven Education in Nigeria](https://www.r-consortium.org/blog/2024/03/19/offa-r-users-group-empowering-data-driven-education-in-nigeria) [ARCHIVE]

The R Consortium had a conversation with Anietie Edem Udokang, who is the founder and organizer of the Offa R Users Group (ORUG). He discussed the emerging local R community…


### [R-Ladies Goiânia: Promoting Diversity and Inclusion in Local R Community](https://www.r-consortium.org/blog/2024/03/13/r-ladies-goiania-promoting-diversity-and-inclusion-in-local-r-community) [ARCHIVE]

Fernanda Kelly, founder and organizer of the R-Ladies Goiânia, recently talked to the R Consortium about the group’s efforts to provide a learning and networking platform to gender and ethnic…


### [ISC-funded Grant: Secure TLS Connections in {nanonext} and {mirai} Facilitating High-Performance Computing in the Life Sciences](https://www.r-consortium.org/blog/2024/03/12/isc-funded-grant-secure-tls-connections-in-nanonext-and-mirai-facilitating-high-performance-computing-in-the-life-sciences) [ARCHIVE]

Contributed by Charlie Gao, Director at Hibiki AI Limited {nanonext} is an R binding to the state of the art C messaging library NNG (Nanomsg Next Generation), created as a…


### [The Cleveland R User Group’s Journey Through Pandemic Adaptations and Baseball Analytics](https://www.r-consortium.org/blog/2024/03/07/the-cleveland-r-user-groups-journey-through-pandemic-adaptations-and-baseball-analytics) [ARCHIVE]

Last year, R Consortium talked to John Blischak and Tim Hoolihan of the Cleveland R User Group about their regular structured and casual virtual meetups during the pandemic. Recently, Alec…


### [Apply Now! R Consortium Infrastructure Steering Committee (ISC) Grant Program Open for Proposals!](https://www.r-consortium.org/blog/2024/03/01/apply-now-r-consortium-infrastructure-steering-committee-isc-grant-program-open-for-proposals) [ARCHIVE]

Help build R infrastructure! We're opening the call for proposals for the 2024 Infrastructure Steering Committee (ISC) Grant Program. The R Consortium is dedicated to enriching the R Ecosystem, directly…


### [The R Consortium 2023: A Year of Growth and Innovation](https://www.r-consortium.org/blog/2024/02/28/the-r-consortium-2023-a-year-of-growth-and-innovation) [ARCHIVE]

Excerpted from the Annual Report Access the annual report here! Letter from the Chair — Mehar Pratap Singh, Chairman Welcome to the 2023 Annual Report of the R Consortium. This…


### [Moffitt Cancer Center Bio-Data Club’s New Chapter in Spatial Data Analysis and Enhanced Hackathon Collaboration](https://www.r-consortium.org/blog/2024/02/27/moffitt-cancer-center-bio-data-clubs-new-chapter-in-spatial-data-analysis-and-enhanced-hackathon-collaboration) [ARCHIVE]

The R Consortium recently reconnected with Paul Stewart, founder of Moffitt Cancer Center Bio-Data Club in Tampa, Florida. Since the last update on January 6th, 2023, the Moffitt Cancer Center…


### [Recap: R Validation Hub Community Meeting](https://www.r-consortium.org/blog/2024/02/23/recap-r-validation-hub-community-meeting) [ARCHIVE]

Join the R Validation Hub mailing list! The recent R Validation Hub Community meeting brought together around 50 participants to explore the concept of "validation" within the R programming ecosystem.…


### [Join our R/Medicine Webinar: Quarto for Reproducible Medical Manuscripts](https://www.r-consortium.org/blog/2024/02/21/join-our-r-medicine-webinar-quarto-for-reproducible-medical-manuscripts) [ARCHIVE]

Join the R Consortium for an enlightening webinar on March 20th, 2024, at 4:00 PM ET, featuring Mine Cetinkaya-Rundel, Professor of the Practice of Statistical Science at Duke University. Discover…


### [R-Ladies Cotonou – A Community that Makes R Accessible for French-Speaking African Women](https://www.r-consortium.org/blog/2024/02/20/r-ladies-cotonou-a-community-that-makes-r-accessible-for-french-speaking-african-women) [ARCHIVE]

Nadejda Sero, the founder of the R Ladies Cotonou chapter, shared with the R Consortium her experiences learning R, the challenges of running an R community in a developing country,…


### [Unlocking the Power of R for Insurance and Actuarial Science: Webinar Series Recap](https://www.r-consortium.org/blog/2024/02/14/unlocking-the-power-of-r-for-insurance-and-actuarial-science-webinar-series-recap) [ARCHIVE]

The R Consortium recently hosted a webinar series tailored specifically for insurance and actuarial science professionals. This series, called the R/Insurance webinar series, led by experts Georgios Bakoloukas and Benedikt…


### [Ann Arbor R User Group: Harnessing the Power of R and GitHub](https://www.r-consortium.org/blog/2024/02/13/ann-arbor-r-user-group-harnessing-the-power-of-r-and-github) [ARCHIVE]

The R Consortium talked to Barry Decicco, founder, and organizer of the Ann Arbor R User Group, based in Ann Arbor, Michigan. Barry shared his experience working with R as…


### [Unraveling the term “Validation”: Join the Discussion at the R Validation Hub Community Meeting on February 20, 2024 ](https://www.r-consortium.org/blog/2024/02/12/unraveling-the-term-validation-join-the-discussion-at-the-r-validation-hub-community-meeting-on-february-20-2024) [ARCHIVE]

Dive into the world of validation at the first R Validation Hub community meeting of the year! What defines a validated R package? Is it ensuring reproducibility across systems? Prioritizing…


### [R Consortium Infrastructure Steering Committee (ISC) Grant Program Accepting Proposals starting March 1st!](https://www.r-consortium.org/blog/2024/02/08/r-consortium-infrastructure-steering-committee-isc-grant-program-accepting-proposals-starting-march-1st) [ARCHIVE]

The R Consortium is excited to announce the opening of our call for proposals for the 2024 Infrastructure Steering Committee (ISC) Grant Program on March 1st, 2024. This initiative is…


### [Improving with R: Kylie Bemis Unveils Enhanced Signal Processing with Matter 2.4 Upgrade](https://www.r-consortium.org/blog/2024/02/07/improving-with-r-kylie-bemis-unveils-enhanced-signal-processing-with-matter-2-4-upgrade) [ARCHIVE]

The R Consortium recently connected with Kylie Bemis, assistant teaching professor at the Khoury College of Computer Sciences at Northeastern University. She has a keen interest in statistical computing frameworks…


### [Join Our Upcoming Webinar: Master Tidy Finance & Access Financial Data with Expert Christoph Scheuch](https://www.r-consortium.org/announcement/2024/02/06/join-our-upcoming-webinar-master-tidy-finance-access-financial-data-with-expert-christoph-scheuch) [ARCHIVE]

Are you passionate about financial economics and eager to learn more about empirical research methods? Then our upcoming webinar is an unmissable opportunity for you! Discover Tidy Finance: A Revolutionary…


### [Natalia Andriychuk on RUGs, Pfizer R Center of Excellence, and Open Source Projects: Fostering R Communities Inside and Out](https://www.r-consortium.org/blog/2024/02/02/natalia-andriychuk-on-rugs-pfizer-r-center-of-excellence-and-open-source-projects-fostering-r-communities-inside-and-out) [ARCHIVE]

The R Consortium recently talked with Natalia Andriychuk, Statistical Data Scientist at Pfizer and co-founder of the RTP R User Group (Research Triangle Park in Raleigh, North Carolina), to get…


### [Webinar for R and Databases!  How Oracle Machine Learning for R Helps with ML and Massive Datasets](https://www.r-consortium.org/blog/2024/01/30/webinar-for-r-and-databases-how-oracle-machine-learning-for-r-helps-with-ml-and-massive-datasets) [ARCHIVE]

Are you seeking faster R data processing and enhanced machine learning capabilities for massive datasets in databases? Look no further. Join us in our upcoming webinar to discover how Oracle…


### [2024 RUGS Program Progress: Reviewing Grants and Empowering R Communities](https://www.r-consortium.org/blog/2024/01/24/2024-rugs-program-progress-reviewing-grants-and-empowering-r-communities) [ARCHIVE]

Quick update on the 2024 R User Groups (RUGS) Program. The review of the first batch of grants is in progress, marking the beginning of the awarding phase. But there’s…


### [Join “Fake it Until You Make it: How and Why to Simulate Data” – First Glasgow User Group Event of the Year](https://www.r-consortium.org/blog/2024/01/19/join-fake-it-until-you-make-it-how-and-why-to-simulate-data-first-glasgow-user-group-event-of-the-year) [ARCHIVE]

Last year, Antonio Hegar of the R Glasgow user group shared the challenges of organizing an R user group in Glasgow. The group now regularly hosts events, attracting local R…


### [Satellite Data with R: Unveiling Earth’s Surface Using the ICESat2R Package](https://www.r-consortium.org/blog/2024/01/16/satellite-data-with-r-unveiling-earths-surface-using-the-icesat2r-package) [ARCHIVE]

The R Consortium recently connected with Lampros Sp. Mouselimis, the creator of the ICESat2R package, discussing the ICESat-2 mission, a significant initiative in understanding the Earth's surface dynamics. This NASA…


### [Rebooting the Warsaw R Community in 2024: Insights from Kamil Sijko’s Journey and Future Aspirations](https://www.r-consortium.org/blog/2024/01/15/rebooting-the-warsaw-r-community-in-2024-insights-from-kamil-sijkos-journey-and-future-aspirations) [ARCHIVE]

Recently, Kamil Sijko of the Warsaw R User Group discussed with the R Consortium his transition from academia to leading data science in the business sector. He noted the current…


### [From Vision to Action: Pfizer’s R Adoption Odyssey – Join the Webinar on February 8, 2024](https://www.r-consortium.org/blog/2024/01/12/from-vision-to-action-pfizers-r-adoption-odyssey-join-the-webinar-on-february-8-2024) [ARCHIVE]

In the rapidly evolving sphere of pharmaceutical data analysis, a significant transition is taking place – the shift from traditional SAS to the versatile R programming language. Pfizer, a trailblazer…


### [R for Public Health Data Analysis in Karachi, Pakistan](https://www.r-consortium.org/blog/2024/01/10/r-for-public-health-data-analysis-in-karachi-pakistan) [ARCHIVE]

The Karachi R User Group, Pakistan, hosted its second event, “Unveiling the Power of R Shiny Dashboards,” on December 30, 2023. The R Consortium spoke with Uzair Aslam, the group’s…


### [Financial Assistance is Available for Your R User Group in 2024!](https://www.r-consortium.org/blog/2024/01/08/financial-assistance-is-available-for-your-r-user-group-in-2024) [ARCHIVE]

The R Consortium is excited to open the doors to the 2024 RUGS Program, starting January 8th, 2024! We are committed to supporting R User Groups (RUGS) worldwide in your…


### [Harness the Power of R for Survival Analysis: Join Our {ggsurvfit} Webinar!](https://www.r-consortium.org/blog/2024/01/04/harness-the-power-of-r-for-survival-analysis-join-our-ggsurvfit-webinar) [ARCHIVE]

Hello, Data Enthusiasts! Are you ready to take your data visualization skills to the next level in the fascinating world of survival analysis? We're thrilled to invite you to our…


### [How Inclusivity, Women in STEM, and Trips to the Pub Together Enrich the Manchester R User Group in the UK](https://www.r-consortium.org/blog/2024/01/02/how-inclusivity-women-in-stem-and-trips-to-the-pub-together-enrich-the-manchester-r-user-group-in-the-uk) [ARCHIVE]

Zac Nash and Abbie Brookes, co-founders of MancR (left), and Jeremy Horne (right), Director of Datacove The R Consortium recently reached out to Abbie Brookes, Senior Analyst and AI Consultant…

# [R Consortium blog archive (2015-2024)](https://www.r-consortium.org/news/blog)