# R User Groups, Conferences, and Special Project Grants

This page describes how to apply for grants to support R user groups, conferences featuring R, and R Special Projects.

For any problems or information, please email [operations@r-consortium.org](#)


# 2024 RUGS Program

The RUGS mission is to facilitate the person-to-person exchange of knowledge in small group settings on a global scale. We continue to believe that the most effective way for people to learn from and about each other, and to set and accomplish common goals is to meet face-to-face on a regular basis. Nevertheless, occasional virtual meetings are acceptable. 

RUGS grants are intended to help people form enduring R user group communities. Active user groups may apply for grants once every calendar year. 

The R Consortium RUGS Program has grown from being a relatively modest R user group support program to being the primary vehicle for the R Consortium to award Social Infrastructure Grants. Social Infrastructure includes meetings, events, conferences, and other activities to strengthen the R Community. 

These grants do not include support for software development or technical projects. Grants to support the R ecosystem’s technical infrastructure are awarded and administered through the [ISC Grant Program](https://www.r-consortium.org/all-projects/call-for-proposals), which issues a call for proposals two times each year.


### 📌 Find your local R User Group [here](https://www.meetup.com/pro/r-user-groups/)


---


# Structure 

In 2024, there will be three categories of RUGS Program grants that are described in detail below:



1. User Group Grants
2. Conference Grants 
3. Special Projects Grants


### Duration of the 2024 RUGS Program

The 2024 RUGS Program will open on January 8, 2024, and close at midnight PST on September 30, 2024. We reserve the right to close the grant window earlier than anticipated based on the number of applications. 


### How to apply for a RUGS Program Grant

To apply for a grant [fill out this form](https://forms.gle/gJMZuq8KxmzrCnuTA). Be sure to select the correct box to indicate whether you are applying for a use group, conference, or special projects grant.

 


# User Group Grants


### Requirements

To be eligible for a RUGS grant, a user group must:



1. Group Organizer must have at least five people in the R User Group
2. Have R as a primary focus
3. Adhere to the [Code of Conduct](https://events.linuxfoundation.org/about/code-of-conduct/?__hstc=98577409.44d7f16716270a3b9b81de6d864e02dc.1720553161514.1721159359293.1721164323976.8&__hssc=98577409.4.1721164323976&__hsfp=1019891917) published on the R Consortium website
4. Agree to participate in the RUGS meetup.com Pro program and use their meetup.com site to announce and track meetings
5. Acknowledge the R Consortium as a sponsor and display the R Consortium logo on the group’s website
6. Agree to write at least two blog posts per year about their group’s activities for possible publication on the R Consortium Blog
7. Comply with the instructions by completing a W9 Form (US-based groups only) or Wire Transfer form (Groups based outside of the US)
8. Agree to the above in a grant agreement via DocuSign


### Structure

R user groups grants under the RUGS 2024 program come in two parts:



1. R user groups that are not already participating in the RUGS meetup.com Pro account will be enrolled into this program. The R Consortium will pay the group’s meetup.com fees for twelve months after acceptance into the program. Thereafter, the R Consortium will continue to pay meetup.com dues for participating groups as long as the groups comply with the requirements above, remain active, continue to meet at least once every three months, and use meetup.com to schedule and announce meetings. User group organizers do not need to re-apply for meetup.com Pro account participation if the group’s meetup.com account remains active.
2. Cash grants typically vary between $200 and $1,000 and depend on group size and special needs.


# General Requirements



1. Must agree to write 2 blog posts a year
2. Post photos of their meetings onto Meetup.com as appropriate
3. Upload available material to the [R Consortium GitHub Repository](https://github.com/RConsortium/rugs-materials)


# RUGs Grant Amounts and Groups’ Responsibilities 

Brand new R User Group



* The group receives a grant of $250 and membership in Meetup pro
* The group must show 5 people committed to the group
* R Consortium will provide the blog link and best practice guide
* The group must agree to write two blog posts per year

To get a grant of up to $500, all of the above plus:



* The group must meet at least 1 time every 3 months
* The group must have more than 25 people at the meeting
* The group must have photos of the meeting 
* The group must show R Consortium Sponsorship

To get a grant of up to $1,000, all of the above plus:



* The group must meet at least twice every 3 months
* The group must have more than 50 people at the meeting
* The group should provide [presentations available for others](https://github.com/RConsortium/rugs-materials) (The R Consortium will host on [GitHub](https://github.com/RConsortium/rugs-materials))


### Notes



1. R-Ladies maintains a separate meetup.com Pro account. R-Ladies groups must apply directly to R-Ladies for acceptance into their program. They will not be automatically entered into the RUGS meetup.com Pro account.
2. The R Consortium maintains the right to terminate the RUG’s Pro program at any time. Additionally, The R Consortium has the right to terminate a group’s participation in the meetup.com Pro program if they do not comply with the requirements specified in the Code of Conduct.


# 2024 Conference Grants

To qualify for a RUGS program conference grant, an event must be focused on the R language, offer at least one full day of technical talks and presentations, and aim to attract participants with diverse backgrounds. RUGS conference grants are for conferences organized by non-profit or volunteer groups. If you seek a sponsorship for your professional event, please contact sponsorship@r-consortium.org.

For good examples of conferences, please see [Bioconductor](https://eurobioc2023.bioconductor.org/), [Rencontres](https://rr2023.sciencesconf.org/), and [LatinR](https://latin-r.com/).


# Requirements


### To be eligible for consideration, a conference must:



* Be organized around the R Language or demonstrate that there will be significant R content.
* Have a web page that provides basic typical information such as:
    * The theme or purpose of the conference
    * The date, time and location of the conference
    * Registration fees listed for classes of attendees (e.g. corporate, student etc.) and mechanism for people to register
    * Sponsorship details (R Consortium logo should not be posted until grant is approved and contract is signed) along with details on classes of sponsorship and any associated benefits
    * A list of sponsors or alternate sources of funding
    * A section on how to submit talks and a mechanism for people to submit talks
    * A list of keynote speakers (if any)
    * A schedule of talks and events
    * A list of confirmed speakers
    * Information about travel and housing
    * A code of conduct that uses or is compatible with the R Consortium’s [Code of Conduct](https://events.linuxfoundation.org/about/code-of-conduct/?__hstc=98577409.44d7f16716270a3b9b81de6d864e02dc.1720553161514.1721159359293.1721164323976.8&__hssc=98577409.4.1721164323976&__hsfp=1019891917) that provides information about how conference participants can report violations or seek help


### After Receiving a Grant



* Applicants must submit billing documentation (W9 or wire transfer form) within one week of contract signature.
* Conference organizers must:
    * Acknowledge the R Consortium as a sponsor and display the R Consortium logo on the conference website.
    * Provide at least one full admission ticket for an R Consortium member.
    * Write a short report after the conference summarizing what happened, describing highlights, and providing key metrics for the conference, including demographics for the attendees, in a way that would be suitable for publication as an R Consortium blog post.
    * Offer the R Consortium the same benefits that the conference offers to other sponsors at the same level of support.
    * Comply with local Covid-19 public health protocols.


Note

Any grant relating to a specific activity will be canceled if (a) the activity to which it relates is canceled without rescheduling or (b) the activity has otherwise not occurred within 365 days of the grant date. 


# Special Projects Grants

We do not believe that these kinds of events comprise everything that can be done to support the R Community. With our Special Projects Grants categories, we hope to stimulate the imagination of local R community builders.


# Requirements


### A request for a special purpose grant must take the form of a formal proposal and include:



* A business case for the project
* A description of how it will benefit the R Community
* A description of who will participate
* The cost to participate
* Explaining how it will happen
* Listing the work products that might result
* Detailing when and where the project will happen
* Listing who will manage and produce the project
* Detailing how much it will cost
* Include a detailed breakdown of how grant money will be spent
* Have a Code of Conduct 


### After Receiving a Grant



* Applicants must submit billing documentation (W9 or wire transfer form) within one week of contract signature
* Acknowledge the R Consortium as a sponsor and display the R Consortium logo on any associated online websites or promotional material
* Applicant billing information must match applicant contact information
* Participants must:
    * Event participants must adhere to the Code of Conduct
    * Comply with local COVID-19 public health protocols


### Also, note that any training materials developed with R Consortium funds must be made publically available with an open source license.


### How to Apply for a RUGS, Conference, or Special Projects Grant

Apply for a grant by filling out [this form](https://forms.gle/8MRf5uw3xQUz4pXx9). Be sure to select the correct box on the form that indicates whether you are applying for a RUGS grant, a conference grant, or a special projects grant
