# **Submitting for payment**

The R Consortium provides financial support to a broad range of initiatives, in support of the global R development and user community. When organizations become members of the R Consortium, their membership dues help provide this funding, and help ensure the overall health of the ecosystem.

The R Consortium provides funding through a structured process. The primary funding categories are:



* [ISC Grants](https://www.r-consortium.org/all-projects/awarded-projects), which are allocated by the Infrastructure Steering Committee through an application process, and support code and community development efforts.
* [RUGs Grants](https://www.r-consortium.org/all-projects/r-user-group-support-program), which support local R User Groups.

All grant payments must be pre-approved. Please follow the formal process established by each working group to apply for funding.


### Invoicing for your grant

Starting in October 2020, each grant recipient will receive a control number. Please ensure that you include this in all requests for payment. If you are unsure of your control number, please contact operations@r-consortium.org.

When you are ready to submit for payment, please complete the [payment request form](http://grant-invoices.r-consortium.org/). You will be asked to provide the following, so please have it ready:



* The control number for your grant.
* A [W9 form](https://www.irs.gov/pub/irs-pdf/fw9.pdf) (if you are in the US and have a SSN/EIN) or an [international wire form](https://wire-transfer.r-consortium.org).
* The signed contract or a PDF of the email approving your grant.
* A brief description of how the funding was used (e.g., project milestone, RUGs or R-Ladies meetup, etc).

If you have any questions, please contact [operations@r-consortium.org](#).
