---
title: "The R Consortium 2023: A Year of Growth and Innovation"
description: "Excerpted from the Annual Report Access the annual report here! Letter from the Chair — Mehar Pratap Singh, Chairman Welcome to the 2023 Annual Report of the R Consortium. This…"
author: "R Consortium"
date: "02/28/2024"
---

_Excerpted from the Annual Report_

### [Access the annual report here!](https://www.r-consortium.org/r-consortium-annual-report-2023)

_Letter from the Chair — Mehar Pratap Singh, Chairman_

Welcome to the 2023 Annual Report of the R Consortium. This document reflects a year of significant growth, innovation, and community engagement within and beyond the R ecosystem. As we present the accomplishments and milestones of the past year, we also set our sights forward, laying out the path for an even more collaborative and impactful future.  

The R Consortium serves as a central hub for the R community, bringing together industry leaders, academic institutions, and individual contributors to foster the development and proliferation of the R language. Our mission is to support the R community through funding, infrastructure improvement, community initiatives, and global outreach.  

In 2023, the R Consortium played a pivotal role in shaping the development of the R ecosystem. Through monetary grants, nearly $200,000 dollars to develop R packages and other technical infrastructure, through fostering industry wide collaborative working groups, and by supporting R-Ladies, R user groups, and several important industry conferences, including Latin-R, New York R, and Bioconductor conferences. This report highlights some of these achievements, showcasing the collective effort of our members and the broader community.  

Recognizing the dynamic nature of data science technologies and the evolving needs of industry, we also recognize the responsibility of the R Consortium to help set a vision for the evolution of the R ecosystem. As you read through this report, we hope you’ll appreciate the strides we’ve made together and feel inspired by the potential of what we can achieve in the future. The R Consortium is more than just an organization: it’s a vibrant community of innovators, problem-solvers, and thought leaders. Together, we are shaping a future where the power of R is accessible to all and continues to drive progress across industries worldwide.   

Thank you for your continued support and dedication to the R Consortium and the wider R community. 

### [Access the annual report here!](https://www.r-consortium.org/r-consortium-annual-report-2023)