---
title: "Enhancing Clinical Trial Data Sharing with R Consortium’s R Submissions Working Group"
description: "The R Consortium’s working group R Submissions Working Group is spearheading an innovative approach to clinical trial data sharing, according to a feature in Nature."
author: "R Consortium"
date: "05/29/2024"
---

The R Consortium’s working group [R Submissions Working Group](https://github.com/RConsortium/submissions-wg) is spearheading an innovative approach to clinical trial data sharing, according to a feature in Nature. This initiative, led by Eric Nantz, a statistician at Eli Lilly in Indianapolis, Indiana, involves a pilot project with the US Food and Drug Administration (FDA). Sharing clinical trial data traditionally requires each scientist to install custom computational dashboards, a cumbersome and error-prone process.

Nantz elaborates on the benefits of using webR and WebAssembly in this context: “Using WebAssembly, [it] will minimize, from the reviewer’s perspective, many of the steps that they had to take to get the application running on their machines.” This technology not only simplifies the data sharing process but also has the potential to accelerate drug approval timelines and enhance collaborative research across various fields.

For more details, read the full article on Nature’s website:[ Read the full article here](https://www.nature.com/articles/d41586-024-00725-1) (Paid subscription required).

To further explore Eric Nantz’s insights on using R and Shiny in regulatory submissions, you can also check out the [R/Adoption Series: R and Shiny in Regulatory Submissions with Eric Nantz.](https://www.youtube.com/watch?v=wKG8VyZg6V0)




